-- MySQL Script generated by MySQL Workbench
-- Sat Jun 22 22:00:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema site_de_marcacao_de_consulta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site_de_marcacao_de_consulta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site_de_marcacao_de_consulta` DEFAULT CHARACTER SET utf8 ;
USE `site_de_marcacao_de_consulta` ;

-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`analista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`analista` (
  `id_analista` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT(11) NOT NULL,
  `user_id_user1` INT(11) NOT NULL,
  PRIMARY KEY (`id_analista`),
  INDEX `fk_table1_area1_idx` (`area_id` ASC),
  INDEX `fk_analista_user1_idx` (`user_id_user1` ASC),
  CONSTRAINT `fk_analista_user1`
    FOREIGN KEY (`user_id_user1`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta` (
  `id_da_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_da_consulta`),
  INDEX `fk_consulta_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_consulta_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta_paciente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `consulta_id_da_consulta` INT(11) NOT NULL,
  `paciente_id_paciente` INT(11) NOT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(50) NOT NULL DEFAULT 'pendente',
  `posicao` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consulta_paciente_consulta1_idx` (`consulta_id_da_consulta` ASC),
  INDEX `fk_consulta_paciente_paciente1_idx` (`paciente_id_paciente` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`funcionario` (
  `id_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `ultimo_nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `administrador` INT(11) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`doctor` (
  `id_doctor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT(11) NOT NULL,
  `user_id_user` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_doctor`),
  INDEX `fk_doctor_area1_idx` (`area_id` ASC),
  INDEX `fk_doctor_user1_idx` (`user_id_user` ASC),
  INDEX `fk_doctor_funcionario1_idx` (`funcionario_id` ASC),
  CONSTRAINT `fk_doctor_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta_paciente_has_doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta_paciente_has_doctor` (
  `id_consulta_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `consulta_paciente_id` INT(11) NOT NULL,
  `doctor_id_doctor` INT(11) NOT NULL,
  PRIMARY KEY (`id_consulta_paciente`),
  INDEX `fk_consulta_paciente_has_doctor_consulta_paciente1_idx` (`consulta_paciente_id` ASC),
  INDEX `fk_consulta_paciente_has_doctor_doctor1_idx` (`doctor_id_doctor` ASC),
  CONSTRAINT `fk_consulta_paciente_has_doctor_consulta_paciente1`
    FOREIGN KEY (`consulta_paciente_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`consulta_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_paciente_has_doctor_doctor1`
    FOREIGN KEY (`doctor_id_doctor`)
    REFERENCES `site_de_marcacao_de_consulta`.`doctor` (`id_doctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`paciente` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `historico_medico` VARCHAR(45) NULL DEFAULT NULL,
  `user_id_user` INT(11) NOT NULL,
  `bilhete` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_paciente_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_paciente_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
