z-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 11:44:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site_marcaçao_de_consulta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site_marcaçao_de_consulta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site_marcaçao_de_consulta` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `site_marcação_de_consulta` ;

-- -----------------------------------------------------
-- Table `site_marcaçao_de_consulta`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`Consulta` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `id da área` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_marcação_de_consulta`.`Consulta_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`Consulta_paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_paciente` VARCHAR(45) NOT NULL,
  `id_consulta` VARCHAR(45) NULL,
  `id_Doctor` VARCHAR(45) NOT NULL,
  `data_consulta` VARCHAR(45) NOT NULL,
  `data_de control` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_marcaçao_de_consulta`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`Paciente` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `peso` VARCHAR(45) NULL,
  `morada` VARCHAR(45) NULL,
  `numero do bi` VARCHAR(45) NULL,
  `Consulta_paciente_has_Doctor_id` INT NOT NULL,
  `Consulta_paciente_has_Doctor_id_paciente` INT NOT NULL,
  `Consulta_paciente_has_Doctor_id_consulta` INT NOT NULL,
  `Consulta_paciente_id` INT NOT NULL,
  `Consulta_paciente_Consulta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Consulta_paciente_has_Doctor_id`, `Consulta_paciente_has_Doctor_id_paciente`, `Consulta_paciente_has_Doctor_id_consulta`, `Consulta_paciente_id`, `Consulta_paciente_Consulta_id`),
  INDEX `Consulta_paciente1_idx` (`Consulta_paciente_id` ASC, `Consulta_paciente_Consulta_id` ASC) VISIBLE,
  CONSTRAINT `Consulta_paciente`
    FOREIGN KEY (`Consulta_paciente_id`)
    REFERENCES `site_marcaçao_de_consulta`.`Consulta_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_marcaçao_de_consulta`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`Doctor` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Especializaçao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_marcaçao_de_consulta`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Administrador` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_marcaçao_de_consulta`.`Consulta_paciente_has_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_marcaçao_de_consulta`.`Consulta_paciente_has_Doctor` (
  `Consulta_paciente_id` INT NOT NULL,
  `Consulta_paciente_Consulta_id` INT NOT NULL,
  `Doctor_id` INT NOT NULL,
  PRIMARY KEY (`Consulta_paciente_id`, `Consulta_paciente_Consulta_id`, `Doctor_id`),
  INDEX `fk_Consulta_paciente_has_Doctor_Doctor1_idx` (`Doctor_id` ASC) VISIBLE,
  INDEX `fk_Consulta_paciente_has_Doctor_Consulta_paciente1_idx` (`Consulta_paciente_id` ASC, `Consulta_paciente_Consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_paciente_has_Doctor_Consulta_paciente1`
    FOREIGN KEY (`Consulta_paciente_id`)
    REFERENCES `site_marcaçao_de_consulta`.`Consulta_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_paciente_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `site_marcaçao_de_consulta`.`Doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`area` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Consulta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Consulta_id`),
  INDEX `fk_área_Consulta_idx` (`Consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_área_Consulta`
    FOREIGN KEY (`Consulta_id`)
    REFERENCES `site_marcaçao_de_consulta`.`Consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
