-- MySQL Script generated by MySQL Workbench
-- Mon May 13 20:06:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site_de_marcacao_de_consulta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site_de_marcacao_de_consulta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site_de_marcacao_de_consulta` DEFAULT CHARACTER SET utf8 ;
USE `site_de_marcacao_de_consulta` ;

-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta` (
  `id_da_consulta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id_da_consulta`),
  INDEX `fk_consulta_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_consulta_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`analise` (
  `id_da_analise` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id_da_analise`),
  INDEX `fk_analise_area1_idx` (`area_id` ASC),
  CONSTRAINT `fk_analise_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `administrador` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `historico_medico` VARCHAR(45) NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_paciente_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_paciente_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta_paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id_da_consulta` INT NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consulta_paciente_consulta1_idx` (`consulta_id_da_consulta` ASC),
  INDEX `fk_consulta_paciente_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_consulta_paciente_consulta1`
    FOREIGN KEY (`consulta_id_da_consulta`)
    REFERENCES `site_de_marcacao_de_consulta`.`consulta` (`id_da_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_paciente_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `site_de_marcacao_de_consulta`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`analise_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`analise_paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analise_id_da_analise` INT NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_analise_paciente_analise1_idx` (`analise_id_da_analise` ASC),
  INDEX `fk_analise_paciente_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_analise_paciente_analise1`
    FOREIGN KEY (`analise_id_da_analise`)
    REFERENCES `site_de_marcacao_de_consulta`.`analise` (`id_da_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analise_paciente_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `site_de_marcacao_de_consulta`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`doctor` (
  `id_doctor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_doctor`),
  INDEX `fk_doctor_area1_idx` (`area_id` ASC),
  INDEX `fk_doctor_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_doctor_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`consulta_paciente_has_doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`consulta_paciente_has_doctor` (
  `id_consulta_paciente` INT NOT NULL AUTO_INCREMENT,
  `consulta_paciente_id` INT NOT NULL,
  `doctor_id_doctor` INT NOT NULL,
  PRIMARY KEY (`id_consulta_paciente`),
  INDEX `fk_consulta_paciente_has_doctor_consulta_paciente1_idx` (`consulta_paciente_id` ASC),
  INDEX `fk_consulta_paciente_has_doctor_doctor1_idx` (`doctor_id_doctor` ASC),
  CONSTRAINT `fk_consulta_paciente_has_doctor_consulta_paciente1`
    FOREIGN KEY (`consulta_paciente_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`consulta_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_paciente_has_doctor_doctor1`
    FOREIGN KEY (`doctor_id_doctor`)
    REFERENCES `site_de_marcacao_de_consulta`.`doctor` (`id_doctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`analista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`analista` (
  `id_analista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area_id` INT NOT NULL,
  `user_id_user1` INT NOT NULL,
  PRIMARY KEY (`id_analista`),
  INDEX `fk_table1_area1_idx` (`area_id` ASC),
  INDEX `fk_analista_user1_idx` (`user_id_user1` ASC),
  CONSTRAINT `fk_table1_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `site_de_marcacao_de_consulta`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analista_user1`
    FOREIGN KEY (`user_id_user1`)
    REFERENCES `site_de_marcacao_de_consulta`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_de_marcacao_de_consulta`.`analise_paciente_has_analista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_de_marcacao_de_consulta`.`analise_paciente_has_analista` (
  `id_analise_paciente` INT NOT NULL AUTO_INCREMENT,
  `analista_id_analista` INT NOT NULL,
  `analista_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_analise_paciente`),
  INDEX `fk_analise_paciente_has_analista_analista1_idx` (`analista_id_analista` ASC, `analista_user_id_user` ASC),
  CONSTRAINT `fk_analise_paciente_has_analista_analista1`
    FOREIGN KEY (`analista_id_analista`)
    REFERENCES `site_de_marcacao_de_consulta`.`analista` (`id_analista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
